name: dbdapy
dependencies:
- backports=1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2=py35_1
- fontconfig=2.11.1=5
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_3
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyzmq=15.2.0=py35_1
- qt=4.8.7=3
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- scipy=0.17.1=np111py35_0
- seaborn=0.7.0=py35_0
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.8
  - babel==2.3.4
  - backports.shutil-get-terminal-size==1.0.0
  - commonmark==0.5.4
  - docutils==0.12
  - imagesize==0.7.1
  - joblib==0.9.4
  - nbsphinx==0.2.8
  - numpydoc==0.6.0
  - patsy==0.4.1
  - pymc3==3.0
  - recommonmark==0.4.0
  - snowballstemmer==1.2.1
  - sphinx==1.4.4
  - theano==0.8.2
